### ISSUE TITLE
FLUTTER PROYECT

### ISSUE THREAD

**Issue by lolito0012** [zTomz/Uno-Card-Game#1]
hi Tom, im trying to do an app (flutter) for a game card. I have all the code neccesary to play offline( against bots ) , now im trying to implement the online mode (Firebase) ,at this point i have implemented the part of teh code dedicated for create a room and join a room, but i dont know how to put all the players of the room at the same game screen and also idk how to sincronizate a rol(index) for each player ... if u can help me , im pretty noob in this "world" 😅 🥹

**Comment by zTomz** [comment]
Hi Lolito, sorry for the very late answer. I think, for synchronizing all players, you can create a collection for every room in firebase and use a StreamBuilder in your Flutter Widget to get notified on every change. If you want me to help you with that, I will need to know, how your firebase firestore is structured.
